# Security headers for the Control Plane panel.
#
# This policy governs **the panel only**. It says nothing about the applications
# users deploy: Opanel does not impose a content policy on a customer's workload
# (Annex C §14).
Rails.application.configure do
  config.content_security_policy do |policy|
    policy.default_src :self
    policy.base_uri    :self
    policy.font_src    :self, :data
    policy.img_src     :self, :data
    policy.object_src  :none
    policy.script_src  :self

    # `unsafe-inline` for styles only, and deliberately.
    #
    # The imported component library positions floating elements — popovers,
    # tooltips, scroll areas, progress bars — by writing to `element.style` at
    # runtime. CSP governs that as an inline style, and a nonce cannot cover it:
    # a nonce authorizes a `<style>` element, not a CSSOM mutation. Under
    # `style-src 'self'` the browser blocks the write and the components render
    # wrong, which is how this was found (M00-08's gallery journey).
    #
    # `script_src` stays strict, which is the directive that matters: inline
    # script is code execution, inline style is presentation. Removing this needs
    # a component library that never touches `element.style` — an upstream
    # change, not a configuration one.
    policy.style_src   :self, :unsafe_inline

    policy.connect_src :self

    # Clickjacking. `frame_ancestors :none` is the header form of X-Frame-Options
    # and the one browsers actually honour for nested contexts.
    policy.frame_ancestors :none
    policy.form_action :self

    if Rails.env.development?
      # The Vite dev server is a separate origin, and HMR opens a websocket back
      # to it. React Refresh evaluates the modules it swaps in. None of this
      # applies to a built asset, so it stays scoped to development.
      vite_origin = ViteRuby.config.host_with_port

      # `unsafe_inline` as well: @vitejs/plugin-react installs its React Refresh
      # preamble as an inline script, and without it every module fails to
      # evaluate — the page loads and React never mounts. A nonce cannot cover it,
      # because the tag is generated by the Vite integration rather than by a
      # helper that could carry one.
      #
      # Development only. Production and test keep `script-src 'self'`, which a
      # spec asserts.
      policy.script_src(*policy.script_src, :unsafe_eval, :unsafe_inline, "http://#{vite_origin}")
      policy.style_src(*policy.style_src, :unsafe_inline, "http://#{vite_origin}")
      policy.connect_src(*policy.connect_src, "http://#{vite_origin}", "ws://#{vite_origin}")
      policy.img_src(*policy.img_src, "http://#{vite_origin}")

      # Webfonts too. `@fontsource-*` ships `.woff2` files that Vite serves from
      # its own origin in development, and without this `font-src 'self'` blocks
      # every one of them: the panel silently falls back to the system sans and
      # no font the design system declares is ever seen locally. A built asset is
      # served by Rails, from the same origin, so this stays scoped here.
      policy.font_src(*policy.font_src, "http://#{vite_origin}")
    end
  end
end

Rails.application.config.action_dispatch.default_headers.merge!(
  # Do not leak the panel's paths — which name teams, projects and services — to
  # anything a user navigates to.
  "Referrer-Policy" => "strict-origin-when-cross-origin",
  "X-Content-Type-Options" => "nosniff",
  # The panel has no reason to reach any of these.
  "Permissions-Policy" => "camera=(), microphone=(), geolocation=(), payment=(), usb=()"
)

# HSTS is applied by `config.force_ssl` in production, which also redirects and
# marks cookies secure. It is deliberately not set here: sending HSTS from an
# environment that is not served over TLS locks a developer out of their own
# machine.
